// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-Xwt8PkKHoY4iPmLd8aaCLBrk678itI',
    appId: '1:152814192001:web:ea6677b2becc99eed99480',
    messagingSenderId: '152814192001',
    projectId: 'dyoevents-b1aca',
    authDomain: 'dyoevents-b1aca.firebaseapp.com',
    storageBucket: 'dyoevents-b1aca.appspot.com',
    measurementId: 'G-KHHTDZE81E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3p0rTboRZKgjMk6dLiVrCugic8ewwwQ',
    appId: '1:152814192001:android:0dcad987b0be0a36d99480',
    messagingSenderId: '152814192001',
    projectId: 'dyoevents-b1aca',
    storageBucket: 'dyoevents-b1aca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV-pQinKIHoe1mqx8h0zY4LYQFr6FX_h4',
    appId: '1:152814192001:ios:a31bc2a97556efdfd99480',
    messagingSenderId: '152814192001',
    projectId: 'dyoevents-b1aca',
    storageBucket: 'dyoevents-b1aca.appspot.com',
    iosClientId:
        '152814192001-92gk1ecqlen2tneqnp9br6f8o94u9jl9.apps.googleusercontent.com',
    iosBundleId: 'ch.dyoevents.dierberger.dominik.dyoevents20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV-pQinKIHoe1mqx8h0zY4LYQFr6FX_h4',
    appId: '1:152814192001:ios:a31bc2a97556efdfd99480',
    messagingSenderId: '152814192001',
    projectId: 'dyoevents-b1aca',
    storageBucket: 'dyoevents-b1aca.appspot.com',
    iosClientId:
        '152814192001-92gk1ecqlen2tneqnp9br6f8o94u9jl9.apps.googleusercontent.com',
    iosBundleId: 'ch.dyoevents.dierberger.dominik.dyoevents20',
  );
}
